services:
  lora_monitor:
    build: .
    environment:
      - MQTT_SERVER=localhost
      - MQTT_PORT=1883
      - MQTT_TOPIC=lora/
      - TEMPERATURE_TOPIC=bridge/temperature
      - UPTIME_TOPIC=bridge/uptime
      - SERIAL_URL=/dev/ttyS0
      - SERIAL_BAUDRATE=9600
    devices:
      - "/dev/ttyS0:/dev/ttyS0"
    restart: unless-stopped
    user: root
    healthcheck:
      test: ["CMD", "./healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
